version: '3'
services:
  webapp:
    #build: .
    image: lazyxxxx/webfortest:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=hospitaldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Xu123456

  db:
    image: lazyxxxx/mysqlfortest:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Xu123456
      - MYSQL_DATABASE=hospitaldb
    ports:
      - "3306:3306"
    # volumes:
    #   - hospital_db-data:/var/lib/mysql
  
# volumes:
#   hospital_db-data:
